messages = [
        "I'll be famous one day, but for now I'm stuck in middle school with a bunch of morons.",
        "If there's one thing I learned from Rodrick, it's to set people's expectations real low so you end up surprising them by practically doing nothing at all.",
        "You can't expect everyone to have the same dedication as you.",
        "Monkeys can't talk, stupid!",
        "The best person I know is Myself.",
        "So if you want to find somebody to blame for the way i am, I guess you'd have to start with the public education system.",
        "Zoo-Wee Mama!",
        "I didn't really know what to expect from detention but when I waked into the room, the first thought I had was, I don't belong in here with these future criminals.",
        "See, when you're a little kid, nobody ever warns you that you've got an expiration date. One day you're hot stuff and the next day you're a dirt sandwich.",
        "For the record, I think it should be illegal for a boy to have to fold his mother's underwear.",
        "Well, the problem is, it's not easy for me to think of ways to improve myself, because I'm pretty much one of the best people I know.",
        "I'm not really sure what makes a book a 'classic' to begin with, but I think it has to be at least fifty years old and some person or animal has to die at the end.",
        "So I've started wearing sweatpants to bed because I really don't need Santa seeing me in my underwear.",
        "YO MOMMA",
        "You and your group of nerds fall into a pit and it's full of dynamite and you blow up. The End.",
        "First of all, let me get this straight: This is a JOURNAL, not a diary. I know what it says on the cover, but when Mom went out to buy this thing I SPECIFICALLY told her to get one that didn't say 'diary' on it.",
        "I don't know if this makes me a bad person or whatever, but it's hard for me to get interested in other people's vacations.",
        "It's not easy to writing thank-you notes for the stuff you didn't want in the first place.",
        "But the thing I’m finding out is some people don’t really appreciate it when you’r trying to be helpful.",
        "Youre gonna grow up and marry some ice cream! Haha!",
        "I'm basically one of the best people I know.",
        "I realised all the good ideas were taken before I was even born.",
        "Loded Diaper",
        "Chirag: Rowley, do you think I exist? \ Rowley: Nope! I can't even hear you or see you!",
        "Your-pa dad-pa smells-pa like-pa a woman-pa!",
        "Susan: Are you having fun? \ Greg: YEAH! \ Susan: No video games for a week!",
        "My mom said to just be myself, and everyone would like me.",
        "That would be good advice if you were somebody else.",
]


